In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


# NUMPY

In [2]:
import numpy as np

arr = np.array([4,7,8,9])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
print(arr)

[4 7 8 9]


In [4]:
print(arr[3])

9


In [5]:
print(arr[-2])

8


In [7]:
print(arr[0:4])

[4 7 8 9]


In [8]:
print(arr[0:4:2])

[4 8]


In [10]:
print(arr[-1:-4:-1])

[9 8 7]


In [11]:
print(arr.ndim)

1


In [13]:
arr = np.array(4)
print(arr.ndim)

0


In [19]:
arr = np.array([[[4,7,8],[2,3,5]]])

In [20]:
print(arr.ndim)

3


In [21]:
print(arr)

[[[4 7 8]
  [2 3 5]]]


In [24]:
arr = np.array([4,7,8], ndmin = 5)

In [25]:
print(arr.ndim)

5


In [26]:
print(arr)

[[[[[4 7 8]]]]]


In [27]:
arr = np.array([4,7,8,9])

print(arr.dtype)

int64


In [28]:
arr = np.array([4,7,8,9], dtype = "i")

print(arr.dtype)

int32


In [29]:
arr = np.array([4,7,8,9, 11,23, 6], dtype = "f")

In [30]:
print(arr.dtype)

float32


In [31]:
print(arr)

[4. 7. 8. 9.]


In [33]:
print(arr.astype('i'))
print(arr)

[4 7 8 9]
[4. 7. 8. 9.]


In [35]:
arr = np.array([[4,7,8],[4,7,9]])
print(arr[0,1])

7


In [36]:
print(arr[1,1])

7


In [37]:
print(arr[1,2])

9


In [39]:
print(arr[0:2,0:2])

[[4 7]
 [4 7]]


In [46]:
arr = np.array([[4,5,6],[7,8,9]])
print(arr[0:2,-1:-4:-1])

[[6 5 4]
 [9 8 7]]


In [47]:
import os
os.getcwd()

'C:\\Users\\alire\\Data Science Course - 55H'

In [ ]:
cd