In [ ]:
# Open the file in read ('r') mode
file = open('file.txt', 'r')

In [ ]:
# Open the file using 'with' in read ('r') mode
with open('file.txt', 'r') as file:
    # further code

## Reading the entire content

In [ ]:
# Reading and Storing the Entire Content of a File
# Using the read method, you can retrieve the complete content of a file
# and store it as a string in a variable for further processing or display.
# Step 1: Open the file you want to read
with open('file.txt', 'r') as file:
    # Step 2: Use the read method to read the entire content of the file
    file_stuff = file.read()
    # Step 3: Now that the file content is stored in the variable 'file_stuff',
    # you can manipulate or display it as needed.
    # For example, let's print the content to the console:
    print(file_stuff)
# Step 4: The 'with' statement automatically closes the file when it's done,
# ensuring proper resource management and preventing resource leaks.

## Reading the content line by line

In [ ]:
file = open('file.txt', 'r')

line1 = file.readline()  # Reads the first line
line2 = file.readline()  # Reads the second line

In [ ]:
# looping through lines

while True:
    line = file.readline()
    if not line:
        break  # Stop when there are no more lines to read
    print(line)

In [1]:
import pandas as pd

In [2]:
# List of lines to write to the file
Lines = ["This is line 1", "This is line 2", "This is line 3"]
# Create a new file Example3.txt for writing
with open('Example3.txt', 'w') as file2:
    for line in Lines:
        file2.write(line + "\n")
    # file2 is automatically closed when the 'with' block exits

In [3]:
# Data to append to the existing file
new_data = "This is line C"
# Open an existing file Example2.txt for appending
with open('Example2.txt', 'a') as file1:
    file1.write(new_data + "\n")
    # file1 is automatically closed when the 'with' block exits

In [4]:
new_data = "This is line D"

# Open an existing file Example2.txt for appending
with open('Example2.txt', 'a') as file1:
    file1.write(new_data + "\n")
    # file1 is automatically closed when the 'with' block exits

### Copying contents from one file to another

In [ ]:
# Open the source file for reading
with open('source.txt', 'r') as source_file:
    #open the distination file for writing
    with open('destination.txt', 'w') as destination_file:
        # Read lines from the source file and copy them to the destination file
        for line in source_file:
            destination_file.write(line)
    # Destination file is automatically closed when the 'with' block exits
# Source file is automatically closed when the 'with' block exits

## writing files

In [5]:
exmp2 = 'Example2.txt'
with open(exmp2, 'w') as writefile:
    writefile.write("This is line A")

In [6]:
with open(exmp2, 'r') as testwritefile:
    print(testwritefile.read())

This is line A


In [7]:
with open(exmp2, 'w') as writefile:
    writefile.write("This is line A\n")
    writefile.write("This is line B\n")

In [8]:
# Check whether write to file

with open(exmp2, 'r') as testwritefile:
    print(testwritefile.read())

This is line A
This is line B



In [9]:
Lines = ["This is line A\n", "This is line B\n", "This is line C\n"]
Lines

['This is line A\n', 'This is line B\n', 'This is line C\n']

In [11]:
with open('Example2.txt', 'w') as writefile:
    for line in Lines:
        print(line)
        writefile.write(line)

This is line A

This is line B

This is line C



### Appending Files

In [14]:
with open('Example2.txt', 'a') as testwritefile:
    testwritefile.write("This is line C\n")
    testwritefile.write("This is line D\n")
    testwritefile.write("This is line E\n")

In [15]:
with open('Example2.txt', 'r') as testwritefile:
    print(testwritefile.read())

This is line A
This is line B
This is line C
This is line C
This is line D
This is line E
This is line C
This is line D
This is line E



In [16]:
# r+ : Reading and writing. Cannot truncate the file.
# w+ : Writing and reading. Truncates the file.
# a+ : Appending and Reading. Creates a new file, if none exists. You dont have to dwell on the specifics of each mode for this lab.

In [18]:
with open('Example2.txt', 'a+') as testwritefile:
    testwritefile.write("This is line E\n")
    print(testwritefile.read())

## copy the file Example2.txt to the file Example3.txt:

In [19]:
with open('Example2.txt','r') as readfile:
    with open('Example3.txt','w') as writefile:
          for line in readfile:
                writefile.write(line)

In [21]:
# Verify if the copy is successfully executed

with open('Example3.txt','r') as testwritefile:
    print(testwritefile.read())

This is line A
This is line B
This is line C
This is line C
This is line D
This is line E
This is line C
This is line D
This is line E
This is line E
This is line E



## Pandas

In [ ]:
import pandas as pd
# Read the CSV file into a DataFrame
df = pd.read_csv('your_file.csv')

In [32]:
import pandas as pd

# Create a Series from a list
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s.iloc[4])

50


In [33]:
print(s[2])

30


In [34]:
print(type(s))

<class 'pandas.core.series.Series'>


In [35]:
print(len(s))

5


In [36]:
print(s.iloc[3])

40


In [37]:
print(s.iloc[1:4])

1    20
2    30
3    40
dtype: int64


In [39]:
# Creating DataFrames from Dictionaries

import pandas as pd

data = {'name' : ['alice', 'john', 'sarah'],
'age' : [24, 35, 51], 'city': ['new york', 'san francisco', 'athen']}
        
df = pd.DataFrame(data)

print(df)

    name  age           city
0  alice   24       new york
1   john   35  san francisco
2  sarah   51          athen


In [40]:
# colum selection

print(df['age'])

0    24
1    35
2    51
Name: age, dtype: int64


In [41]:
print(df.iloc[2])

name    sarah
age        51
city    athen
Name: 2, dtype: object


In [42]:
print(df.iloc[1])

name             john
age                35
city    san francisco
Name: 1, dtype: object


In [45]:
# slicing

print(df[['name', 'age']])

    name  age
0  alice   24
1   john   35
2  sarah   51


In [49]:
# show rows
print(df[1:3])

    name  age           city
1   john   35  san francisco
2  sarah   51          athen


In [50]:
# show column

print(df['city'])

0         new york
1    san francisco
2            athen
Name: city, dtype: object


In [54]:
# conditional filtering 

age_above_25 = df[df['age'] > 25]

print(age_above_25)

    name  age           city
1   john   35  san francisco
2  sarah   51          athen


In [55]:
# saving DataFrames

df.to_csv('trading_data.csv', index=False)

In [56]:
# Define a dictionary 'x'

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [59]:
type(x)

pandas.core.series.Series

In [63]:
x = df['Name']
x

0    Rose
1    John
2    Jane
3    Mary
Name: Name, dtype: object

In [64]:
type(x)

pandas.core.series.Series

In [69]:
# Access to multiple columns

z = df[['Department', 'Salary']]
z

Department  Salary
0  Architect Group  100000
1   Software Group   80000
2      Design Team   50000
3   Infrastructure   60000

In [71]:
# exercise 
a = {'Student':['David', 'Samuel', 'Terry', 'Evan'],
     'Age':['27', '24', '22', '32'],
     'Country':['UK', 'Canada', 'China', 'USA'],
     'Course':['Python','Data Structures','Machine Learning','Web Development'],
     'Marks':['85','72','89','76']}

df1 = pd.DataFrame(a)
df1

Student Age Country            Course Marks
0   David  27      UK            Python    85
1  Samuel  24  Canada   Data Structures    72
2   Terry  22   China  Machine Learning    89
3    Evan  32     USA   Web Development    76

In [74]:
b = df1['Marks']
b

0    85
1    72
2    89
3    76
Name: Marks, dtype: object

In [75]:
c = df1[['Country','Course']]
c

Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [76]:
x = df1['Student']
x

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: object

In [77]:
type(x)

pandas.core.series.Series

In [78]:
df.iloc[0, 0]

'Rose'

In [79]:
df.iloc[1,3]

80000

In [80]:
df.loc[1,'Salary']

80000

In [82]:
#set the "Name" column as an index

df2 = df
df2 = df2.set_index('Name')

In [83]:
#To display the first 5 rows of new dataframe
df2.head()

ID       Department  Salary
Name                             
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [84]:
df2.loc['Jane', 'Salary']

50000

In [85]:
df2.loc['Jane', 'Department']

'Design Team'

In [88]:
# select rows from Rose to Jane and columns from ID to Department

df2.loc['Rose':'Jane', 'ID':'Department']

ID       Department
Name                     
Rose   1  Architect Group
John   2   Software Group
Jane   3      Design Team

In [90]:
# select rows van index 1 to 2 and colums 1,2 and 3

df2.iloc[0:2, 0:3]

ID       Department  Salary
Name                             
Rose   1  Architect Group  100000
John   2   Software Group   80000

In [91]:
# select rows index 0 and 1, and colums ID and Department

df.loc[0:2,'ID':'Department']

ID       Department
0   1  Architect Group
1   2   Software Group
2   3      Design Team

In [93]:
# Define a dictionary 'x'

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [94]:
# loc werkt op basis van label and iloc werkt op basis van index
df.loc[2:3,  'Name':'Department']

Name  ID      Department
2  Jane   3     Design Team
3  Mary   4  Infrastructure

In [101]:
# Dataset aanmaken als lijst van dictionaries
data = [
    {"OrderID": 1, "Product": "Laptop", "Category": "Electronics", "Quantity": 2, "Price": 800, "Total": 1600, "OrderDate": "2022-01-10", "CustomerCity": "New York"},
    {"OrderID": 2, "Product": "Smartphone", "Category": "Electronics", "Quantity": 3, "Price": 600, "Total": 1800, "OrderDate": "2022-02-15", "CustomerCity": "Los Angeles"},
    {"OrderID": 3, "Product": "Desk Chair", "Category": "Furniture", "Quantity": 5, "Price": 150, "Total": 750, "OrderDate": "2022-03-12", "CustomerCity": "Chicago"},
    {"OrderID": 4, "Product": "Notebook", "Category": "Stationery", "Quantity": 10, "Price": 2, "Total": 20, "OrderDate": "2022-04-05", "CustomerCity": "Houston"},
    {"OrderID": 5, "Product": "Monitor", "Category": "Electronics", "Quantity": 1, "Price": 300, "Total": 300, "OrderDate": "2022-05-21", "CustomerCity": "Miami"},
]

# DataFrame aanmaken
df = pd.DataFrame(data)

In [102]:
df

OrderID     Product     Category  Quantity  Price  Total   OrderDate  \
0        1      Laptop  Electronics         2    800   1600  2022-01-10   
1        2  Smartphone  Electronics         3    600   1800  2022-02-15   
2        3  Desk Chair    Furniture         5    150    750  2022-03-12   
3        4    Notebook   Stationery        10      2     20  2022-04-05   
4        5     Monitor  Electronics         1    300    300  2022-05-21   

  CustomerCity  
0     New York  
1  Los Angeles  
2      Chicago  
3      Houston  
4        Miami

In [103]:
df.head()

OrderID     Product     Category  Quantity  Price  Total   OrderDate  \
0        1      Laptop  Electronics         2    800   1600  2022-01-10   
1        2  Smartphone  Electronics         3    600   1800  2022-02-15   
2        3  Desk Chair    Furniture         5    150    750  2022-03-12   
3        4    Notebook   Stationery        10      2     20  2022-04-05   
4        5     Monitor  Electronics         1    300    300  2022-05-21   

  CustomerCity  
0     New York  
1  Los Angeles  
2      Chicago  
3      Houston  
4        Miami

In [104]:
x = df[['Quantity']]
x

Quantity
0         2
1         3
2         5
3        10
4         1

In [106]:
x = df['Product']
x

0        Laptop
1    Smartphone
2    Desk Chair
3      Notebook
4       Monitor
Name: Product, dtype: object

In [107]:
y = df[['Product','Category', 'Quantity']]
y

Product     Category  Quantity
0      Laptop  Electronics         2
1  Smartphone  Electronics         3
2  Desk Chair    Furniture         5
3    Notebook   Stationery        10
4     Monitor  Electronics         1

In [108]:
df.iloc[0, 0]

1

In [109]:
df.iloc[0, 2]

'Electronics'

In [110]:
df.iloc[2,2]

'Furniture'

In [111]:
df.loc[0, 'Product']

'Laptop'

In [112]:
df.loc[1, 'CustomerCity']

'Los Angeles'

In [113]:
df.loc[1, 'Total']

1800

In [114]:
df.iloc[0:2, 0:3]

OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics

In [116]:
df.loc[0:2, 'OrderID':'Category']

OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics
2        3  Desk Chair    Furniture

In [117]:
q = df['Price']
q

0    800
1    600
2    150
3      2
4    300
Name: Price, dtype: int64

In [118]:
q = df[['Product','Category']]
q

Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics
2  Desk Chair    Furniture
3    Notebook   Stationery
4     Monitor  Electronics

In [119]:
q = df.loc[2:3]
q

OrderID     Product    Category  Quantity  Price  Total   OrderDate  \
2        3  Desk Chair   Furniture         5    150    750  2022-03-12   
3        4    Notebook  Stationery        10      2     20  2022-04-05   

  CustomerCity  
2      Chicago  
3      Houston

In [121]:
new_index = ['a', 'b', 'c', 'd', 'e']
df_new = df
df_new.index = new_index

df_new.loc['a', 'CustomerCity']

'New York'

In [122]:
df_new.loc['a':'d', 'CustomerCity']

a       New York
b    Los Angeles
c        Chicago
d        Houston
Name: CustomerCity, dtype: object

In [127]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [133]:
b.ndim

2

In [135]:
b.size

6

In [136]:
b.shape

(2, 3)

In [128]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [129]:
type(a)

numpy.ndarray

In [130]:
a.dtype

dtype('int32')

In [131]:
a.size

5

In [143]:
a.ndim

1

In [144]:
c = np.array([1.4, 2.4, 5.7, 6.2])

In [146]:
c.dtype

dtype('float64')

In [147]:
c = np.array([20, 1,2,3,4])

In [148]:
c

array([20,  1,  2,  3,  4])

In [149]:
c[0] = 100
c

array([100,   1,   2,   3,   4])

In [150]:
c[4] = 7

In [151]:
c


array([100,   1,   2,   3,   7])

In [152]:
d = c[1:4]
d

array([1, 2, 3])

In [153]:
c[3:5] = 300,400
c

array([100,   1,   2, 300, 400])

In [154]:
y = np.array([1,2])

z = 2 * y
z

array([2, 4])

In [156]:
u = np.array([1,0])
v = np.array([0,1])

In [157]:
z = u - v

In [158]:
z

array([ 1, -1])

In [159]:
u = np.array([1,0])
v = np.array([0,1])

z = u + v
z

array([1, 1])